apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomove-back
  namespace: development-ecomove
  labels:
    app: ecomove
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecomove
  template:
    metadata:
      labels:
        app: ecomove
    spec:
      containers:
        - name: containers-ecomove
          image: jdavidperalta/backend-pipeline:0.0.1
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: backend-secret
