apiVersion: v1
kind: Service
metadata:
  name: ecomove-svc
  namespace: development-ecomove
  labels:
    app: ecomove-svc
spec:
  type: ClusterIP
  ports:
    - name: backend
      port: 3000
      targetPort: 3001
      protocol: TCP
  selector:
    app: ecomove
