apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomove-back-images
  namespace: development-ecomove
  labels:
    app: ecomove-images

spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecomove-images
  template: 
    metadata:
      labels:
        app: ecomove-images
    spec:
      containers:
        - name: containers-ecomove-images
          image: jdavidperalta/backend-images:0.0.6
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: images-secret
