apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: ecomove-front-ingress
  namespace: development-ecomove
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: ecomove.local
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: ecomove-front-svc
            port:
              number: 80
